title:            CAIS++
description:      "Student Blog"
logo:             caislogonewred.png
logowhite:        caislogowhite.png
disqus_shortname: http-caisplusplus-usc-edu-blog
share:            true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  https://caisplusplus.usc.edu

# Owner/author information
owner:
  name:           CAIS++
  avatar:         circle.png
  email:          caisplus@usc.edu
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    USC Center for AI in Society's Student Branch
  # Social networking links used in footer. Update and remove as you like.
  twitter: caisplusplus
  facebook: groups/173750813090965/
  github: /caisplusplus
  instagram: CAISplusplus
  youtube: /channel/UCZdRTEPOw33eZ1elmTsF_wg/videos
  # For Google Authorship https://plus.google.com/authorship

# Analytics and webmaster tools stuff goes here
google_analytics: UA-104062474-1
# Already taken care of this with the google[crazy number].html file
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Blog Home
    url: /blog/
    external: false
    icon: home
  - title: Featured Posts
    url: /blog/featured
  - title: Categories
    url: /blog/categories
  - title: About
    url: /blog/about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true

highlighter: rouge
markdown:    kramdown
plugins_dir: [jekyll-paginate]
gems: [jekyll-paginate]
paginate:    5
paginate_path: "/blog/page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'https://caisplusplus.usc.edu'
  relativeLinks: 'https://caisplusplus.usc.edu/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting

          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
